-- Create profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  elo_rating integer default 1200,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create questions table
create table questions (
  id bigint generated by default as identity primary key,
  topic text not null,
  difficulty text not null, -- 'Easy', 'Medium', 'Hard'
  content text not null, -- Question text or LaTeX
  correct_answer text not null, -- Hidden from client via RLS
  options jsonb, -- For multiple choice
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create attempts table
create table attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  question_id bigint references questions(id) not null,
  is_correct boolean not null,
  duration_seconds integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table questions enable row level security;
alter table attempts enable row level security;

-- Policies (Basic examples)
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Questions are viewable by everyone."
  on questions for select
  using ( true );

-- IMPORTANT: Do NOT allow select on 'correct_answer' column for public
-- This requires more advanced setup or using Edge Functions to check answers.
